In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_svmlight_file
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, precision_recall_curve, recall_score, roc_curve, auc, confusion_matrix, classification_report
import numpy as np
import xgboost as xgb

In [3]:
data = load_svmlight_file('data/demo-g3-v2.txt')
X,y=data[0],data[1]
print(X.shape)
# X_s,y_s=resample(X,y,n_samples=150000,replace=False)
X_train,X_test,y_train,y_test = train_test_split(X_s,y_s,test_size=.3,random_state=42)

(168575, 7672)


In [8]:
def model_eva(model,X_test,y_test):
    y_test_pred=model.predict(X_test)
    print('precision_score:',precision_score(y_test,y_test_pred,average='macro'))
    print(confusion_matrix(y_test,y_test_pred).T)
    print(np.unique(y_test,return_counts=True))
    print(np.unique(y_test_pred,return_counts=True))
    print(classification_report(y_test_pred,y_test))
    print("******************************************************************")

In [5]:
# xgb_clf = xgb.XGBClassifier(
#                  colsample_bytree=0.2,
#                  gamma=0.0,
#                  learning_rate=0.01,
#                  max_depth=8,
#                  min_child_weight=1.5,
#                  n_estimators=1000,                                                                  
#                  reg_alpha=0.9,
#                  reg_lambda=0.6,
#                  subsample=0.2,
#                  seed=42,
#                  silent=1)
xgb_clf = xgb.XGBClassifier(
                 colsample_bytree=0.2,
#                  gamma=0.0,
                 learning_rate=0.01,
                 max_depth=8,
#                  min_child_weight=1.5,
                 n_estimators=1000,                                                                  
#                  reg_alpha=0.9,
#                  reg_lambda=0.6,
#                  subsample=0.2,
                 seed=42,
                 silent=1)
xgb_clf.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.2, gamma=0, learning_rate=0.01, max_delta_step=0,
       max_depth=8, min_child_weight=1, missing=None, n_estimators=1000,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=42, silent=1,
       subsample=1)

In [9]:
model_eva(xgb_clf,X_train,y_train)
model_eva(xgb_clf,X_test,y_test)

precision_score: 0.5306832862411817
[[ 2303  1116  1126   825   750   615   437   332   213   149   292]
 [   18   280    19    22    14     7    10     7     3     3     6]
 [  247   274  1616   426   351   315   215   149   113    86   116]
 [  338   357  1112  3495  1269  1235   888   513   384   257   288]
 [ 1138  1076  2500  2956  6223  3171  2744  2067  1551  1247  1619]
 [  254   240   589  1004  1100  3501  1078   922   734   619   597]
 [   23    35    91   149   220   197  1762   156   162   118   119]
 [    3    11    22    43    45    39    42  1216    56    46    42]
 [    0     0     6    10    13     9    20    17   804     9     5]
 [    0     0     1     3     3     8     1     7     7   702     6]
 [  784   739  1708  2311  3104  3663  3707  3907  3723  3766 11839]]
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]), array([ 5108,  4128,  8790, 11244, 13092, 12760, 10904,  9293,  7750,
        7002, 14929]))
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.

In [14]:
def test(model):
    model_eva(model,X_train,y_train)
    model_eva(model,X_test,y_test) 

In [13]:
xgb_clf_100_6_1 = xgb.XGBClassifier(
#                  colsample_bytree=0.2,
#                  gamma=0.0,
                 learning_rate=0.1,
                 max_depth=6,
#                  min_child_weight=1.5,
                 n_estimators=100,                                                                  
#                  reg_alpha=0.9,
#                  reg_lambda=0.6,
#                  subsample=0.2,
                 seed=42,
                 silent=1)
xgb_clf_100_6_1.fit(X_train,y_train)


precision_score: 0.4394426811031533
[[ 1868  1107  1100   817   738   570   418   338   194   147   282]
 [    5    27     3     1     4     4     3     0     1     0     2]
 [  447   379  1144   538   480   393   272   172   143   103   158]
 [  330   327  1249  2780  1323  1227   825   526   351   249   275]
 [ 1247  1122  2568  3180  5528  3262  2793  2023  1474  1189  1552]
 [  305   270   804  1308  1383  3212  1487  1174   992   786   839]
 [   21    26    73   120   187   177   950   205   161   131   111]
 [   12    10    31    76    74    68    70   630    99    66    60]
 [    3     0     4     3     7     5     6     5   247     5     6]
 [    0     0     1     0     5     1     3     4     2   193     2]
 [  905   785  1804  2437  3340  3868  3969  4203  4035  4217 11759]]
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]), array([ 5143,  4053,  8781, 11260, 13069, 12787, 10796,  9280,  7699,
        7086, 15046]))
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.

In [15]:
test(xgb_clf_100_6_1)

precision_score: 0.4691320458454525
[[ 2163  1209  1244   941   877   664   506   372   236   179   339]
 [   13   184    10    11    14     5     3     3     6     5     8]
 [  259   247  1206   393   337   305   204   151   126    70   128]
 [  401   360  1326  3158  1607  1360   927   567   390   266   299]
 [ 1156  1035  2432  3080  5282  3274  2606  1902  1444  1137  1634]
 [  223   217   685  1104  1358  3001  1368  1077   839   706   786]
 [   22    29    56   114   153   173  1116   167   111   105    76]
 [    6    10    34    61    81   102   106   939    88    78    47]
 [    3     4     3     7     7    13    15    12   488    12    14]
 [    2     5     6     7    14    13    17    12    12   469    12]
 [  895   753  1779  2384  3339  3877  3928  4078  3959  4059 11703]]
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]), array([ 5143,  4053,  8781, 11260, 13069, 12787, 10796,  9280,  7699,
        7086, 15046]))
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.

In [16]:
xgb_clf_1000_6_1 = xgb.XGBClassifier(
#                  colsample_bytree=0.2,
#                  gamma=0.0,
                 learning_rate=0.1,
                 max_depth=6,
#                  min_child_weight=1.5,
                 n_estimators=1000,                                                                  
#                  reg_alpha=0.9,
#                  reg_lambda=0.6,
#                  subsample=0.2,
                 seed=42,
                 silent=1)
xgb_clf_1000_6_1.fit(X_train,y_train)
test(xgb_clf_1000_6_1)

precision_score: 0.5432161012671715
[[ 2800   946   969   774   727   547   437   343   202   172   306]
 [   84   847    92    93    67    69    56    36    21    17    33]
 [  352   396  3020   570   549   515   355   235   208   139   222]
 [  314   352  1068  4836  1349  1239   887   585   387   280   352]
 [  649   644  1500  1914  6530  2182  1805  1385  1029   808   877]
 [  231   236   597   920  1017  5012  1085   826   720   575   572]
 [   59    50   150   229   294   270  3118   271   202   176   160]
 [   22    36    86    99   147   143   120  2535   123   123   106]
 [    8    14    34    41    44    48    55    51  1833    35    44]
 [    5    14    14    32    36    46    42    48    41  1849    41]
 [  619   518  1251  1752  2309  2716  2836  2965  2933  2912 12333]]
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]), array([ 5143,  4053,  8781, 11260, 13069, 12787, 10796,  9280,  7699,
        7086, 15046]))
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.

In [18]:
xgb_clf_1000_6_01 = xgb.XGBClassifier(
#                  colsample_bytree=0.2,
#                  gamma=0.0,
                 learning_rate=0.01,
                 max_depth=6,
#                  min_child_weight=1.5,
                 n_estimators=1000,                                                                  
#                  reg_alpha=0.9,
#                  reg_lambda=0.6,
#                  subsample=0.2,
                 seed=42,
                 silent=1)
xgb_clf_1000_6_01.fit(X_train,y_train)
test(xgb_clf_1000_6_01)

precision_score: 0.46939975391103433
[[ 2126  1189  1225   943   873   664   503   373   235   173   335]
 [   10   174    11    16    19    10     3     7     7     5     9]
 [  280   260  1197   386   343   293   199   151   130    77   125]
 [  426   391  1382  3161  1610  1412  1013   580   414   290   349]
 [ 1155  1034  2433  3084  5299  3305  2594  1940  1451  1179  1633]
 [  211   206   656  1084  1314  2917  1386  1049   813   676   758]
 [   19    29    53    98   121   141  1002   127   104    95    62]
 [    4     7    30    58    83    95    93   924    82    68    39]
 [    3     3     2     7     5    10    12     8   478     9     9]
 [    1     4     6     9     9    11    17    11     7   454    11]
 [  908   756  1786  2414  3393  3929  3974  4110  3978  4060 11716]]
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]), array([ 5143,  4053,  8781, 11260, 13069, 12787, 10796,  9280,  7699,
        7086, 15046]))
(array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11