In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_svmlight_file
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import precision_score, precision_recall_curve, recall_score, roc_curve, auc, confusion_matrix,classification_report
import numpy as np
import xgboost as xgb

In [2]:
df=pd.read_json('data/spark-demo-g1.json',lines=True)

In [3]:
df.head()

features  indexedLabel  label  \
0  {'type': 0, 'size': 7672, 'indices': [0, 1, 2,...             0      1   
1  {'type': 0, 'size': 7672, 'indices': [0, 1, 2,...             0      1   
2  {'type': 0, 'size': 7672, 'indices': [0, 1, 2,...             0      1   
3  {'type': 0, 'size': 7672, 'indices': [0, 1, 2,...             0      1   
4  {'type': 0, 'size': 7672, 'indices': [0, 1, 2,...             0      1   

                                         pcaFeatures  predictedLabel  \
0  {'type': 1, 'values': [-22.772430251608046, -3...               1   
1  {'type': 1, 'values': [-204.7509957911829, -27...               1   
2  {'type': 1, 'values': [-215.64825449614676, 5....               2   
3  {'type': 1, 'values': [-29.40938585744219, 4.5...               1   
4  {'type': 1, 'values': [-789.5649316512413, 155...               1   

   prediction                                        probability  \
0           0  {'type': 1, 'values': [0.548231843800501, 0.45...   
1           0  {'type': 1, 'values': [0.687962531136674, 0.31...   
2           1  {'type': 1, 'values': [0.49775465705571104, 0....   
3           0  {'type': 1, 'values': [0.580030631136608, 0.41...   
4           0  {'type': 1, 'values': [0.636738256952869, 0.36...   

                                       rawPrediction  
0  {'type': 1, 'values': [54.82318438005013, 45.1...  
1  {'type': 1, 'values': [68.79625311366748, 31.2...  
2  {'type': 1, 'values': [49.77546570557116, 50.2...  
3  {'type': 1, 'values': [58.00306311366087, 41.9...  
4  {'type': 1, 'values': [63.67382569528697, 36.3...

In [4]:
label = df['label']
predict=df['predictedLabel']

In [5]:
confusion_matrix(label,predict)

array([[13072,  3379],
       [ 6345,  5729]])

In [6]:
precision_score(label,predict)

0.673224494000103

In [7]:
print(np.unique(label,return_counts=True))
print(np.unique(predict,return_counts=True))

(array([1, 2]), array([16451, 12074]))
(array([1, 2]), array([19417,  9108]))


In [10]:
df3=pd.read_json('data/spark-demo-g3.json',lines=True)
label3 = df3['label']
predict3=df3['predictedLabel']

In [11]:
confusion_matrix(label3,predict3)

array([[ 335,    0,   16,   19,  569,   48,    0,    0,    0,    0,  318],
       [ 213,    0,   11,   30,  439,   41,    1,    0,    0,    0,  215],
       [ 215,    0,   21,   93, 1014,  165,    0,    0,    0,    0,  571],
       [ 150,    0,   21,  184, 1285,  283,    0,    0,    0,    0,  753],
       [ 137,    0,   21,  154, 1338,  345,    1,    0,    0,    0, 1148],
       [  93,    0,   13,  128, 1277,  363,    3,    0,    0,    0, 1293],
       [  79,    0,    3,   89,  905,  276,    1,    0,    0,    0, 1160],
       [  56,    0,    8,   45,  690,  222,    4,    0,    0,    0, 1206],
       [  45,    0,    4,   36,  547,  192,    1,    0,    0,    0, 1089],
       [  24,    0,    6,   23,  380,  153,    4,    0,    0,    0, 1106],
       [  56,    0,    9,   19,  686,  196,    0,    0,    0,    0, 2708]])

In [12]:
print(classification_report(label3,predict3))

              precision    recall  f1-score   support

           4       0.24      0.26      0.25      1305
           5       0.00      0.00      0.00       950
           6       0.16      0.01      0.02      2079
           7       0.22      0.07      0.11      2676
           8       0.15      0.43      0.22      3144
           9       0.16      0.11      0.13      3170
          10       0.07      0.00      0.00      2513
          11       0.00      0.00      0.00      2231
          12       0.00      0.00      0.00      1914
          13       0.00      0.00      0.00      1696
          14       0.23      0.74      0.36      3674

   micro avg       0.20      0.20      0.20     25352
   macro avg       0.11      0.15      0.10     25352
weighted avg       0.13      0.20      0.12     25352



/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
print(np.unique(label3,return_counts=True))
print(np.unique(predict3,return_counts=True))

(array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), array([1305,  950, 2079, 2676, 3144, 3170, 2513, 2231, 1914, 1696, 3674]))
(array([ 4,  6,  7,  8,  9, 10, 14]), array([ 1403,   133,   820,  9130,  2284,    15, 11567]))


In [15]:
df3=pd.read_json('data/spark-demo-g3-v2.json',lines=True)
label3 = df3['label']
predict3=df3['predictedLabel']

In [16]:
confusion_matrix(label3,predict3)

array([[ 360,   71,  156,  129,  201,  101,   66,   37,   25,   19,  136],
       [ 222,   41,  105,  109,  124,  101,   52,   39,   14,   12,  122],
       [ 239,   59,  259,  290,  392,  252,  168,   80,   43,   26,  270],
       [ 177,   47,  281,  413,  541,  355,  207,  139,   73,   43,  402],
       [ 190,   37,  262,  446,  584,  470,  300,  179,   99,   68,  532],
       [ 150,   46,  241,  371,  586,  456,  288,  167,   98,   73,  684],
       [  82,   26,  163,  251,  402,  350,  261,  143,   75,   71,  686],
       [  77,   21,  100,  191,  308,  306,  233,  142,   65,   71,  709],
       [  53,   16,  115,  155,  250,  252,  156,   99,   65,   51,  682],
       [  42,   12,   65,  114,  201,  205,  130,   90,   74,   51,  719],
       [  84,   15,  105,  179,  291,  308,  224,  166,  139,  126, 2008]])

In [17]:
print(classification_report(label3,predict3))

              precision    recall  f1-score   support

           4       0.21      0.28      0.24      1301
           5       0.10      0.04      0.06       941
           6       0.14      0.12      0.13      2078
           7       0.16      0.15      0.16      2678
           8       0.15      0.18      0.17      3167
           9       0.14      0.14      0.14      3160
          10       0.13      0.10      0.11      2510
          11       0.11      0.06      0.08      2223
          12       0.08      0.03      0.05      1894
          13       0.08      0.03      0.04      1703
          14       0.29      0.55      0.38      3645

   micro avg       0.18      0.18      0.18     25300
   macro avg       0.15      0.16      0.14     25300
weighted avg       0.16      0.18      0.16     25300



In [18]:
print(np.unique(label3,return_counts=True))
print(np.unique(predict3,return_counts=True))

(array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), array([1301,  941, 2078, 2678, 3167, 3160, 2510, 2223, 1894, 1703, 3645]))
(array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), array([1676,  391, 1852, 2648, 3880, 3156, 2085, 1281,  770,  611, 6950]))
